// <auto-generated />
using FoodDelivery.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodDelivery.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240620055728_FoodItemsSeedAdded")]
    partial class FoodItemsSeedAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodDelivery.API.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Dhaka",
                            Latitude = 40.712800000000001,
                            Longitude = -74.006,
                            Street = "Mirpur"
                        },
                        new
                        {
                            Id = 2,
                            City = "Dhaka",
                            Latitude = 34.052199999999999,
                            Longitude = -118.2437,
                            Street = "Mohammedpur"
                        });
                });

            modelBuilder.Entity("FoodDelivery.API.Models.FoodCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RestaurantMenuId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantMenuId");

                    b.ToTable("FoodCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RestaurantMenuId = 1,
                            Title = "Appetizers"
                        },
                        new
                        {
                            Id = 2,
                            RestaurantMenuId = 1,
                            Title = "Main Courses"
                        },
                        new
                        {
                            Id = 3,
                            RestaurantMenuId = 1,
                            Title = "Desserts"
                        },
                        new
                        {
                            Id = 4,
                            RestaurantMenuId = 2,
                            Title = "Appetizers"
                        },
                        new
                        {
                            Id = 5,
                            RestaurantMenuId = 2,
                            Title = "Main Courses"
                        },
                        new
                        {
                            Id = 6,
                            RestaurantMenuId = 2,
                            Title = "Desserts"
                        },
                        new
                        {
                            Id = 7,
                            RestaurantMenuId = 3,
                            Title = "Appetizers"
                        },
                        new
                        {
                            Id = 8,
                            RestaurantMenuId = 3,
                            Title = "Main Courses"
                        },
                        new
                        {
                            Id = 9,
                            RestaurantMenuId = 3,
                            Title = "Desserts"
                        },
                        new
                        {
                            Id = 10,
                            RestaurantMenuId = 4,
                            Title = "Appetizers"
                        },
                        new
                        {
                            Id = 11,
                            RestaurantMenuId = 4,
                            Title = "Main Courses"
                        },
                        new
                        {
                            Id = 12,
                            RestaurantMenuId = 4,
                            Title = "Desserts"
                        },
                        new
                        {
                            Id = 13,
                            RestaurantMenuId = 5,
                            Title = "Appetizers"
                        },
                        new
                        {
                            Id = 14,
                            RestaurantMenuId = 5,
                            Title = "Main Courses"
                        },
                        new
                        {
                            Id = 15,
                            RestaurantMenuId = 5,
                            Title = "Desserts"
                        },
                        new
                        {
                            Id = 16,
                            RestaurantMenuId = 6,
                            Title = "Appetizers"
                        },
                        new
                        {
                            Id = 17,
                            RestaurantMenuId = 6,
                            Title = "Main Courses"
                        },
                        new
                        {
                            Id = 18,
                            RestaurantMenuId = 6,
                            Title = "Desserts"
                        },
                        new
                        {
                            Id = 19,
                            RestaurantMenuId = 7,
                            Title = "Appetizers"
                        },
                        new
                        {
                            Id = 20,
                            RestaurantMenuId = 7,
                            Title = "Main Courses"
                        },
                        new
                        {
                            Id = 21,
                            RestaurantMenuId = 7,
                            Title = "Desserts"
                        },
                        new
                        {
                            Id = 22,
                            RestaurantMenuId = 8,
                            Title = "Appetizers"
                        },
                        new
                        {
                            Id = 23,
                            RestaurantMenuId = 8,
                            Title = "Main Courses"
                        },
                        new
                        {
                            Id = 24,
                            RestaurantMenuId = 8,
                            Title = "Desserts"
                        },
                        new
                        {
                            Id = 25,
                            RestaurantMenuId = 9,
                            Title = "Appetizers"
                        },
                        new
                        {
                            Id = 26,
                            RestaurantMenuId = 9,
                            Title = "Main Courses"
                        },
                        new
                        {
                            Id = 27,
                            RestaurantMenuId = 9,
                            Title = "Desserts"
                        },
                        new
                        {
                            Id = 28,
                            RestaurantMenuId = 10,
                            Title = "Appetizers"
                        },
                        new
                        {
                            Id = 29,
                            RestaurantMenuId = 10,
                            Title = "Main Courses"
                        },
                        new
                        {
                            Id = 30,
                            RestaurantMenuId = 10,
                            Title = "Desserts"
                        });
                });

            modelBuilder.Entity("FoodDelivery.API.Models.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FoodCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FoodCategoryId");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Crispy spring rolls stuffed with vegetables.",
                            FoodCategoryId = 1,
                            ImageUrl = "https://img.freepik.com/free-photo/margherita-pizza-with-basil-top-view_2829-10397.jpg?w=740",
                            Name = "Spring Rolls",
                            Price = 5.9900000000000002
                        },
                        new
                        {
                            Id = 2,
                            Description = "Freshly grilled salmon with a side of vegetables.",
                            FoodCategoryId = 2,
                            ImageUrl = "https://img.freepik.com/free-photo/spaghetti-carbonara-white-plate_2829-15834.jpg?w=740",
                            Name = "Grilled Salmon",
                            Price = 15.99
                        },
                        new
                        {
                            Id = 3,
                            Description = "Creamy cheesecake with a graham cracker crust.",
                            FoodCategoryId = 3,
                            ImageUrl = "https://img.freepik.com/free-photo/tiramisu-italian-dessert_2829-12651.jpg?w=740",
                            Name = "Cheesecake",
                            Price = 6.9900000000000002
                        },
                        new
                        {
                            Id = 4,
                            Description = "Toasted bread topped with tomatoes and basil.",
                            FoodCategoryId = 1,
                            ImageUrl = "https://img.freepik.com/free-photo/chicken-tikka-masala-with-rice_2829-19349.jpg?w=740",
                            Name = "Bruschetta",
                            Price = 4.9900000000000002
                        },
                        new
                        {
                            Id = 5,
                            Description = "Classic spaghetti with pancetta and a creamy sauce.",
                            FoodCategoryId = 2,
                            ImageUrl = "https://img.freepik.com/free-photo/naan-bread-flat-lay_2829-11117.jpg?w=740",
                            Name = "Spaghetti Carbonara",
                            Price = 12.99
                        },
                        new
                        {
                            Id = 6,
                            Description = "Traditional Italian dessert with coffee and mascarpone.",
                            FoodCategoryId = 3,
                            ImageUrl = "https://img.freepik.com/free-photo/mango-lassi-indian-yogurt-drink_2829-11519.jpg?w=740",
                            Name = "Tiramisu",
                            Price = 5.9900000000000002
                        },
                        new
                        {
                            Id = 7,
                            Description = "Bread with garlic and butter, toasted to perfection.",
                            FoodCategoryId = 1,
                            ImageUrl = "https://img.freepik.com/free-photo/assorted-sushi-set-black-background_2829-15836.jpg?w=740",
                            Name = "Garlic Bread",
                            Price = 3.9900000000000002
                        },
                        new
                        {
                            Id = 8,
                            Description = "Pasta with creamy Alfredo sauce and grilled chicken.",
                            FoodCategoryId = 2,
                            ImageUrl = "https://img.freepik.com/free-photo/miso-soup-wooden-bowl_2829-11711.jpg?w=740",
                            Name = "Chicken Alfredo",
                            Price = 13.99
                        },
                        new
                        {
                            Id = 9,
                            Description = "Rich chocolate cake with a molten chocolate center.",
                            FoodCategoryId = 3,
                            ImageUrl = "https://img.freepik.com/free-photo/matcha-green-tea-ice-cream_2829-12799.jpg?w=740",
                            Name = "Chocolate Lava Cake",
                            Price = 7.9900000000000002
                        },
                        new
                        {
                            Id = 10,
                            Description = "Fried mozzarella cheese sticks with marinara sauce.",
                            FoodCategoryId = 1,
                            ImageUrl = "https://img.freepik.com/free-photo/beef-tacos-with-lemon-slices_2829-13131.jpg?w=740",
                            Name = "Mozzarella Sticks",
                            Price = 6.9900000000000002
                        },
                        new
                        {
                            Id = 11,
                            Description = "Tacos with seasoned beef, lettuce, and cheese.",
                            FoodCategoryId = 2,
                            ImageUrl = "https://img.freepik.com/free-photo/guacamole-dip-with-tortilla-chips_2829-13130.jpg?w=740",
                            Name = "Beef Tacos",
                            Price = 10.99
                        },
                        new
                        {
                            Id = 12,
                            Description = "Vanilla ice cream topped with chocolate sauce and nuts.",
                            FoodCategoryId = 3,
                            ImageUrl = "https://img.freepik.com/free-photo/churros-with-chocolate-sauce_2829-13132.jpg?w=740",
                            Name = "Ice Cream Sundae",
                            Price = 4.9900000000000002
                        },
                        new
                        {
                            Id = 13,
                            Description = "Crispy onion rings with a side of ranch dressing.",
                            FoodCategoryId = 1,
                            ImageUrl = "https://img.freepik.com/free-photo/caesar-salad-white-bowl_2829-13133.jpg?w=740",
                            Name = "Onion Rings",
                            Price = 5.4900000000000002
                        },
                        new
                        {
                            Id = 14,
                            Description = "Slow-cooked ribs with BBQ sauce and coleslaw.",
                            FoodCategoryId = 2,
                            ImageUrl = "https://img.freepik.com/free-photo/grilled-chicken-sandwich_2829-13134.jpg?w=740",
                            Name = "BBQ Ribs",
                            Price = 18.989999999999998
                        },
                        new
                        {
                            Id = 15,
                            Description = "Classic apple pie with a flaky crust.",
                            FoodCategoryId = 3,
                            ImageUrl = "https://img.freepik.com/free-photo/chocolate-cake-slice-white-plate_2829-13135.jpg?w=740",
                            Name = "Apple Pie",
                            Price = 5.9900000000000002
                        },
                        new
                        {
                            Id = 16,
                            Description = "Mushrooms stuffed with cheese and herbs.",
                            FoodCategoryId = 1,
                            ImageUrl = "https://img.freepik.com/free-photo/pad-thai-noodles-with-shrimp_2829-13136.jpg?w=740",
                            Name = "Stuffed Mushrooms",
                            Price = 6.4900000000000002
                        },
                        new
                        {
                            Id = 17,
                            Description = "Grilled lamb chops with mint sauce.",
                            FoodCategoryId = 2,
                            ImageUrl = "https://img.freepik.com/free-photo/spring-rolls-plate_2829-13137.jpg?w=740",
                            Name = "Lamb Chops",
                            Price = 21.989999999999998
                        },
                        new
                        {
                            Id = 18,
                            Description = "Italian dessert made with sweetened cream.",
                            FoodCategoryId = 3,
                            ImageUrl = "https://img.freepik.com/free-photo/mango-sticky-rice_2829-13138.jpg?w=740",
                            Name = "Panna Cotta",
                            Price = 6.9900000000000002
                        },
                        new
                        {
                            Id = 19,
                            Description = "Spicy chicken wings served with blue cheese dip.",
                            FoodCategoryId = 1,
                            ImageUrl = "https://img.freepik.com/free-photo/cheeseburger-fries-plate_2829-13139.jpg?w=740",
                            Name = "Buffalo Wings",
                            Price = 7.9900000000000002
                        },
                        new
                        {
                            Id = 20,
                            Description = "Juicy cheeseburger with lettuce, tomato, and pickles.",
                            FoodCategoryId = 2,
                            ImageUrl = "https://img.freepik.com/free-photo/french-fries-ketchup_2829-13140.jpg?w=740",
                            Name = "Cheeseburger",
                            Price = 9.9900000000000002
                        },
                        new
                        {
                            Id = 21,
                            Description = "Warm brownie topped with ice cream and chocolate sauce.",
                            FoodCategoryId = 3,
                            ImageUrl = "https://img.freepik.com/free-photo/milkshake-glass_2829-13141.jpg?w=740",
                            Name = "Brownie Sundae",
                            Price = 6.4900000000000002
                        },
                        new
                        {
                            Id = 22,
                            Description = "Tortilla chips topped with cheese, jalapenos, and salsa.",
                            FoodCategoryId = 1,
                            ImageUrl = "https://img.freepik.com/free-photo/greek-salad-bowl_2829-13142.jpg?w=740",
                            Name = "Nachos",
                            Price = 7.4900000000000002
                        },
                        new
                        {
                            Id = 23,
                            Description = "Sizzling fajitas with chicken, peppers, and onions.",
                            FoodCategoryId = 2,
                            ImageUrl = "https://img.freepik.com/free-photo/gyro-pita-sandwich_2829-13143.jpg?w=740",
                            Name = "Fajitas",
                            Price = 14.99
                        },
                        new
                        {
                            Id = 24,
                            Description = "Fried dough pastries with cinnamon sugar.",
                            FoodCategoryId = 3,
                            ImageUrl = "https://img.freepik.com/free-photo/baklava-dessert_2829-13144.jpg?w=740",
                            Name = "Churros",
                            Price = 4.9900000000000002
                        },
                        new
                        {
                            Id = 25,
                            Description = "Lightly breaded and fried calamari served with marinara sauce.",
                            FoodCategoryId = 1,
                            ImageUrl = "https://img.freepik.com/free-photo/bbq-ribs-plate_2829-13145.jpg?w=740",
                            Name = "Fried Calamari",
                            Price = 8.9900000000000002
                        },
                        new
                        {
                            Id = 26,
                            Description = "Spanish rice dish with seafood and saffron.",
                            FoodCategoryId = 2,
                            ImageUrl = "https://img.freepik.com/free-photo/coleslaw-salad_2829-13146.jpg?w=740",
                            Name = "Seafood Paella",
                            Price = 19.989999999999998
                        },
                        new
                        {
                            Id = 27,
                            Description = "Rich custard dessert with a caramelized sugar top.",
                            FoodCategoryId = 3,
                            ImageUrl = "https://img.freepik.com/free-photo/cornbread-slices_2829-13147.jpg?w=740",
                            Name = "Creme Brulee",
                            Price = 7.4900000000000002
                        },
                        new
                        {
                            Id = 28,
                            Description = "Potato skins topped with cheese and bacon.",
                            FoodCategoryId = 1,
                            ImageUrl = "https://img.freepik.com/free-photo/vietnamese-pho-noodle-soup_2829-13148.jpg?w=740",
                            Name = "Potato Skins",
                            Price = 6.4900000000000002
                        },
                        new
                        {
                            Id = 29,
                            Description = "Grilled steak served with mashed potatoes.",
                            FoodCategoryId = 2,
                            ImageUrl = "https://img.freepik.com/free-photo/vietnamese-spring-rolls_2829-13149.jpg?w=740",
                            Name = "Steak and Potatoes",
                            Price = 22.989999999999998
                        },
                        new
                        {
                            Id = 30,
                            Description = "Banana split with ice cream, chocolate sauce, and whipped cream.",
                            FoodCategoryId = 3,
                            ImageUrl = "https://img.freepik.com/free-photo/banh-mi-vietnamese-sandwich_2829-13150.jpg?w=740",
                            Name = "Banana Split",
                            Price = 5.9900000000000002
                        });
                });

            modelBuilder.Entity("FoodDelivery.API.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<string>("Cuisine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeliveryTimeInMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPromoted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            Cuisine = "Italian, Mediterranean",
                            DeliveryTimeInMinutes = 45,
                            ImageUrl = "https://img.freepik.com/free-photo/delicious-burger-with-many-ingredients-isolated-white-background-tasty-cheeseburger-splash-sauce_90220-1266.jpg?t=st=1715625020~exp=1715628620~hmac=ee0ee3d2f13079fdde6fceb6505a1c87055ea22bd4f475c0d1b08be27c7556fd&w=740",
                            IsPromoted = true,
                            Name = "Taste of Tuscany",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 1,
                            Cuisine = "Indian, Fusion",
                            DeliveryTimeInMinutes = 50,
                            ImageUrl = "https://img.freepik.com/premium-photo/asian-food-chinese-fried-rice_711483-63.jpg?w=740",
                            IsPromoted = false,
                            Name = "Spice Route",
                            Rating = 3.5
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 1,
                            Cuisine = "Japanese, Sushi",
                            DeliveryTimeInMinutes = 35,
                            ImageUrl = "https://img.freepik.com/free-photo/well-done-steak-homemade-potatoes_140725-3989.jpg?t=st=1715625633~exp=1715629233~hmac=9358f465c2dc38126fd47b036513a1c40175c4e9c5b6f928f1ce67c535ff00a9&w=360",
                            IsPromoted = false,
                            Name = "Sushi Delight",
                            Rating = 3.8999999999999999
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 1,
                            Cuisine = "French, Bakery",
                            DeliveryTimeInMinutes = 40,
                            ImageUrl = "https://img.freepik.com/premium-photo/couscous-with-mussels-shrimps_135427-6342.jpg?w=900",
                            IsPromoted = false,
                            Name = "Cafe Parisienne",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 5,
                            AddressId = 1,
                            Cuisine = "Italian, Pizza",
                            DeliveryTimeInMinutes = 30,
                            ImageUrl = "https://img.freepik.com/free-photo/chicken-skewers-with-slices-sweet-peppers-dill_2829-18813.jpg?t=st=1715625626~exp=1715629226~hmac=00611d8c50b843d7394cae185a955cc6ef6043004e197aeeb52089c3f4c0bbe4&w=900",
                            IsPromoted = false,
                            Name = "Mamma Mia Pizzeria",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 6,
                            AddressId = 1,
                            Cuisine = "Thai, Street Food",
                            DeliveryTimeInMinutes = 55,
                            ImageUrl = "https://img.freepik.com/free-photo/fruit-salad-spilling-floor-was-mess-vibrant-colors-textures-generative-ai_8829-2895.jpg?t=st=1715625620~exp=1715629220~hmac=6b64105071cebcd0c9da994bcbcc88cd3ea991e25a8d072627160539f99099ec&w=360",
                            IsPromoted = true,
                            Name = "Thai Spice",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 7,
                            AddressId = 1,
                            Cuisine = "American, BBQ",
                            DeliveryTimeInMinutes = 45,
                            ImageUrl = "https://img.freepik.com/premium-photo/large-bowl-food-with-fish-vegetables_197463-2405.jpg?w=740",
                            IsPromoted = false,
                            Name = "Smokehouse BBQ",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 8,
                            AddressId = 1,
                            Cuisine = "Mediterranean, Seafood",
                            DeliveryTimeInMinutes = 40,
                            ImageUrl = "https://img.freepik.com/free-photo/baked-chicken-wings-asian-style-tomatoes-sauce-plate_2829-10657.jpg?t=st=1715625611~exp=1715629211~hmac=5c1d6b2f70119d1f65f1fc53eec7e531b920c69faa7f534c7c1cd62d4c7510e1&w=900",
                            IsPromoted = false,
                            Name = "Mediterranean Breeze",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 9,
                            AddressId = 1,
                            Cuisine = "Indian, Bollywood Fusion",
                            DeliveryTimeInMinutes = 50,
                            ImageUrl = "https://img.freepik.com/free-photo/baked-chicken-wings-asian-style-tomatoes-sauce-plate_2829-10657.jpg?t=st=1715625611~exp=1715629211~hmac=5c1d6b2f70119d1f65f1fc53eec7e531b920c69faa7f534c7c1cd62d4c7510e1&w=900",
                            IsPromoted = false,
                            Name = "Bollywood Spice",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 10,
                            AddressId = 1,
                            Cuisine = "Healthy, Salad",
                            DeliveryTimeInMinutes = 35,
                            ImageUrl = "https://img.freepik.com/premium-photo/grilled-pork-beef-steaks-with-chilli-salt-are-falling-down-black-background-barbecue-grill_157927-18741.jpg?w=360",
                            IsPromoted = false,
                            Name = "Green Garden Salad Bar",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 11,
                            AddressId = 1,
                            Cuisine = "Greek, Mediterranean",
                            DeliveryTimeInMinutes = 25,
                            ImageUrl = "https://img.freepik.com/free-photo/greek-gyros-traditional-greek-food-made-beef-meat-tomatoes-onion-tzatziki-sauce-with-potato-fries-served-pita-bread_2829-11257.jpg?w=740&t=st=1715626298~exp=1715629898~hmac=60d1809d987647a0b76f78b07e5fcfb43a647c56dd4fa8a1c1bcb6e52d278c91",
                            IsPromoted = false,
                            Name = "The Greek Corner",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 12,
                            AddressId = 1,
                            Cuisine = "Korean",
                            DeliveryTimeInMinutes = 35,
                            ImageUrl = "https://img.freepik.com/free-photo/traditional-korean-cuisine_1203-1624.jpg?w=740&t=st=1715626333~exp=1715629933~hmac=fe4f6170e5a1619e421eb13cce8f1b404c15d4175891268f98779c26a7158438",
                            IsPromoted = false,
                            Name = "Seoul Food",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 13,
                            AddressId = 1,
                            Cuisine = "French, Café",
                            DeliveryTimeInMinutes = 20,
                            ImageUrl = "https://img.freepik.com/free-photo/french-breakfast-with-croissants-cup-coffee-coffee-beans-orange-juice-poppy-seeds_2829-19440.jpg?w=740&t=st=1715626368~exp=1715629968~hmac=8e5d060d8a8e482276f97e4977a2d508e1b53c1ec9da57cbec646d50bbce27f5",
                            IsPromoted = false,
                            Name = "Café Parisien",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 14,
                            AddressId = 1,
                            Cuisine = "Thai",
                            DeliveryTimeInMinutes = 40,
                            ImageUrl = "https://img.freepik.com/free-photo/spicy-thai-food-with-herb-ingredients_1150-8117.jpg?w=740&t=st=1715626407~exp=1715630007~hmac=2ff788a3b5f04b1d29d152d52bb791f6ecb8b9a7d29d14d248f7be2f3b6a5d66",
                            IsPromoted = false,
                            Name = "Taste of Thailand",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 15,
                            AddressId = 1,
                            Cuisine = "Middle Eastern",
                            DeliveryTimeInMinutes = 50,
                            ImageUrl = "https://img.freepik.com/free-photo/middle-eastern-appetizers-tabule-kibbeh-vegetarian-falafel-spread_2829-14172.jpg?w=740&t=st=1715626443~exp=1715630043~hmac=9c83c5d5c42c6bc29a25a340a43015ad56de69a55bde69f1797b99505ed1c78e",
                            IsPromoted = false,
                            Name = "Middle Eastern Delights",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 16,
                            AddressId = 1,
                            Cuisine = "American, Soul Food",
                            DeliveryTimeInMinutes = 45,
                            ImageUrl = "https://img.freepik.com/free-photo/soul-food-southern-united-states-traditional-southern-food_2829-14630.jpg?w=740&t=st=1715626475~exp=1715630075~hmac=35f8cc327f5f60d736505c0b102b4bbd29f78dd7810e0b82ac8a7277271a9a8d",
                            IsPromoted = false,
                            Name = "Soul Food Shack",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 17,
                            AddressId = 1,
                            Cuisine = "Italian",
                            DeliveryTimeInMinutes = 35,
                            ImageUrl = "https://img.freepik.com/free-photo/top-view-pasta-with-tomato-sauce-meatballs-plate_23-2148575934.jpg?w=740&t=st=1715626510~exp=1715630110~hmac=285b517ff52e67e7ed7ff9aa1aa83c5f13eb3ab5ab07f8a5bc6a88ae0bb75111",
                            IsPromoted = false,
                            Name = "Viva Italia",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 18,
                            AddressId = 1,
                            Cuisine = "Chinese, Dim Sum",
                            DeliveryTimeInMinutes = 40,
                            ImageUrl = "https://img.freepik.com/free-photo/dim-sum-food-dumpling-in-bamboo-steamer-with-dipping-sauces_2829-19348.jpg?w=740&t=st=1715626546~exp=1715630146~hmac=02d0e3ed5e97320b046b85b13e91d0a441b21e60ac629db60db2301768a07e7a",
                            IsPromoted = false,
                            Name = "Dim Sum House",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 19,
                            AddressId = 1,
                            Cuisine = "Caribbean",
                            DeliveryTimeInMinutes = 55,
                            ImageUrl = "https://img.freepik.com/free-photo/caribbean-food-dishes-table_23-2148483890.jpg?w=740&t=st=1715626577~exp=1715630177~hmac=046c3db3d1175edc83e4fabb0ab027ad4263f4b6df4e1a3c0b7c4d76482dbe1d",
                            IsPromoted = false,
                            Name = "Caribbean Flavors",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 20,
                            AddressId = 1,
                            Cuisine = "Mexican, Tacos",
                            DeliveryTimeInMinutes = 30,
                            ImageUrl = "https://img.freepik.com/free-photo/mexican-tacos-tacos-with-meat-tomatoes-onions_2829-13776.jpg?w=740&t=st=1715626615~exp=1715630215~hmac=42a8f604f544e25d80afcb89a68fbc7fa4b280a80cc11b7cf5a2fa4f0c827a20",
                            IsPromoted = false,
                            Name = "La Taqueria",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 21,
                            AddressId = 2,
                            Cuisine = "Vietnamese",
                            DeliveryTimeInMinutes = 35,
                            ImageUrl = "https://img.freepik.com/free-photo/traditional-vietnamese-noodle-soup-pho-with-beef-raw-meat-dark-background_2829-13880.jpg?w=740&t=st=1715626651~exp=1715630251~hmac=60a2dcf1f04aa44e9ae9d7998c71f7b6c80b5a2d66d438b19d4491125406e08d",
                            IsPromoted = false,
                            Name = "Pho King",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 22,
                            AddressId = 2,
                            Cuisine = "Spanish, Tapas",
                            DeliveryTimeInMinutes = 25,
                            ImageUrl = "https://img.freepik.com/free-photo/assorted-spanish-tapas-served-wooden-board_1220-686.jpg?w=740&t=st=1715626690~exp=1715630290~hmac=26863ae94c06cfcadeea2c92080a27b2a07c5648fa4bba491bb7dc59438d4a27",
                            IsPromoted = false,
                            Name = "Tapas Bar",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 23,
                            AddressId = 2,
                            Cuisine = "American, Bagels",
                            DeliveryTimeInMinutes = 20,
                            ImageUrl = "https://img.freepik.com/free-photo/multicolored-bagels-wooden-tray-grey-surface_2829-15295.jpg?w=740&t=st=1715626732~exp=1715630332~hmac=63a15c1bcb5e8d3c27cb74a98c9ef4b2007b141148ce1cfb46489e94d9ffcf35",
                            IsPromoted = false,
                            Name = "Big Apple Bagels",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 24,
                            AddressId = 2,
                            Cuisine = "Indian, Pakistani",
                            DeliveryTimeInMinutes = 45,
                            ImageUrl = "https://img.freepik.com/free-photo/indian-pakistani-food-assorted-set-top-view_2829-12298.jpg?w=740&t=st=1715626768~exp=1715630368~hmac=184ba7a0c6ea709def0f81b61d77ab82cd3535cfe1ab19a91d3c04bdf63ec4f2",
                            IsPromoted = false,
                            Name = "Spice Route",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 25,
                            AddressId = 2,
                            Cuisine = "French, Café",
                            DeliveryTimeInMinutes = 25,
                            ImageUrl = "https://img.freepik.com/free-photo/delicious-crepes-with-banana-nutella-topped-sugar_144627-32437.jpg?w=740&t=st=1715626807~exp=1715630407~hmac=cf6b0a59e9296374bc197a1c79b8b037e8e1dbab50c157b5d239c8e92d9a2553",
                            IsPromoted = false,
                            Name = "Crepe Café",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 26,
                            AddressId = 2,
                            Cuisine = "Brazilian",
                            DeliveryTimeInMinutes = 55,
                            ImageUrl = "https://img.freepik.com/free-photo/brazilian-bbq-wooden-cutting-board_1203-1632.jpg?w=740&t=st=1715626841~exp=1715630441~hmac=cf516223c604e907aeab25f8e11e2b7e8b72d2a36904ea4e5b3cc8f2a7e2f4e7",
                            IsPromoted = false,
                            Name = "Brazilian BBQ",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 27,
                            AddressId = 2,
                            Cuisine = "American, Burgers",
                            DeliveryTimeInMinutes = 20,
                            ImageUrl = "https://img.freepik.com/free-photo/gourmet-burgers-with-homemade-burger-patties_1220-732.jpg?w=740&t=st=1715626876~exp=1715630476~hmac=fc22df2cf09f4a6d3982cf6073181ed36b7ad708306b03a45a589935af47e92f",
                            IsPromoted = false,
                            Name = "Gourmet Burgers",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 28,
                            AddressId = 2,
                            Cuisine = "Hawaiian",
                            DeliveryTimeInMinutes = 30,
                            ImageUrl = "https://img.freepik.com/free-photo/hawaiian-poke-bowl-with-tuna-top-view_2829-10804.jpg?w=740&t=st=1715626911~exp=1715630511~hmac=c9bb2f3da372bf303657e768f6ff669ee8a899d32f482130527c97c3e6b3e3ec",
                            IsPromoted = false,
                            Name = "Hawaiian Poke",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 29,
                            AddressId = 2,
                            Cuisine = "Belgian, Desserts",
                            DeliveryTimeInMinutes = 20,
                            ImageUrl = "https://img.freepik.com/free-photo/belgian-waffles-with-berries-top-view_2829-10998.jpg?w=740&t=st=1715626947~exp=1715630547~hmac=3d4fe69d6b726d9c4b10357df67e7e70ad6c3b8f547af193aeb4edc09cf6e51e",
                            IsPromoted = false,
                            Name = "Belgian Waffles",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 30,
                            AddressId = 2,
                            Cuisine = "Persian",
                            DeliveryTimeInMinutes = 50,
                            ImageUrl = "https://img.freepik.com/free-photo/persian-food-skewer-fried-kebab-saffron-rice-top-view_2829-15440.jpg?w=740&t=st=1715626986~exp=1715630586~hmac=f4083f7f021eabe3ab4c8feefcd5c7e34e5468e9efbe3a30d2d2ec68c2a2d9d4",
                            IsPromoted = false,
                            Name = "Persian Grill",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 31,
                            AddressId = 2,
                            Cuisine = "American, Diner",
                            DeliveryTimeInMinutes = 25,
                            ImageUrl = "https://img.freepik.com/free-photo/classic-american-diner-meal-with-burgers-fries-milkshake_2829-10698.jpg?w=740&t=st=1715627024~exp=1715630624~hmac=0e748d11d1b9824bb29f409615a8158e6741914701a73535bbed1c0d98db83a7",
                            IsPromoted = false,
                            Name = "Classic Diner",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 32,
                            AddressId = 2,
                            Cuisine = "Moroccan",
                            DeliveryTimeInMinutes = 45,
                            ImageUrl = "https://img.freepik.com/free-photo/moroccan-food-tagine-dish_1203-1674.jpg?w=740&t=st=1715627060~exp=1715630660~hmac=46b208318d94979f39b372e18c30d6d9ec25a3f31c897e80bfae4178bb5d738a",
                            IsPromoted = false,
                            Name = "Moroccan Delights",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 33,
                            AddressId = 2,
                            Cuisine = "Italian, Pizza",
                            DeliveryTimeInMinutes = 30,
                            ImageUrl = "https://img.freepik.com/free-photo/pizza-served-wooden-table_1220-671.jpg?w=740&t=st=1715627098~exp=1715630698~hmac=ff92521fa62fa04fc9e96c0a3e04e79b7d3a0d8bdb86a1072e579fb53750b404",
                            IsPromoted = false,
                            Name = "Italian Pizzeria",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 34,
                            AddressId = 2,
                            Cuisine = "Indian",
                            DeliveryTimeInMinutes = 40,
                            ImageUrl = "https://img.freepik.com/free-photo/assorted-indian-cuisine-with-butter-chicken-spicy-prawn-curry-tikka-masala-chicken-served-basmati-rice-naan-bread_1150-21072.jpg?w=740&t=st=1715627136~exp=1715630736~hmac=ecb5fa340b990f6183259ac7f7cccf0c0172780e9174d01bc53710394e04f1ff",
                            IsPromoted = false,
                            Name = "Indian Spice",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 35,
                            AddressId = 2,
                            Cuisine = "Vegetarian, Salads",
                            DeliveryTimeInMinutes = 20,
                            ImageUrl = "https://img.freepik.com/free-photo/gourmet-salads-wooden-bowls-dark-background_2829-11615.jpg?w=740&t=st=1715627175~exp=1715630775~hmac=09cb50d7852e6e2e708b97e14c0b9f7b2e81e37f967222ed8287dbe2748ec30c",
                            IsPromoted = false,
                            Name = "Gourmet Salads",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 36,
                            AddressId = 2,
                            Cuisine = "Italian",
                            DeliveryTimeInMinutes = 30,
                            ImageUrl = "https://img.freepik.com/free-photo/sicilian-italian-pasta-top-view_2829-12130.jpg?w=740&t=st=1715627215~exp=1715630815~hmac=84b32e8a1da4d76c5b2c7ec22e4d3c72224cbe9eaa62eb5f145cf1d84b03f671",
                            IsPromoted = false,
                            Name = "Sicilian Trattoria",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 37,
                            AddressId = 2,
                            Cuisine = "Mediterranean",
                            DeliveryTimeInMinutes = 35,
                            ImageUrl = "https://img.freepik.com/free-photo/mediterranean-cuisine-with-grilled-vegetables_1203-1668.jpg?w=740&t=st=1715627255~exp=1715630855~hmac=95d84d23e268e19932ef2f51abde9e9dbb54efb8db3c0861f7e2601675d13ef6",
                            IsPromoted = false,
                            Name = "Mediterranean Grille",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 38,
                            AddressId = 2,
                            Cuisine = "Vietnamese",
                            DeliveryTimeInMinutes = 30,
                            ImageUrl = "https://img.freepik.com/free-photo/vietnamese-noodle-soup-pho-with-herbs-beef-top-view_2829-15284.jpg?w=740&t=st=1715627296~exp=1715630896~hmac=f24fd6baf6f7b2206d23c49061d1cf46b19f98207f67d8b6bfb0cd004630f8d0",
                            IsPromoted = false,
                            Name = "Vietnamese Kitchen",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 39,
                            AddressId = 2,
                            Cuisine = "Spanish",
                            DeliveryTimeInMinutes = 40,
                            ImageUrl = "https://img.freepik.com/free-photo/spanish-paella-seafood-top-view_2829-11880.jpg?w=740&t=st=1715627334~exp=1715630934~hmac=bd0283f8d084fbfc0a77deaf6aa55da50fe64c84c49e7580b82435de7a0ac4b2",
                            IsPromoted = false,
                            Name = "Spanish Paella",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 40,
                            AddressId = 2,
                            Cuisine = "Egyptian",
                            DeliveryTimeInMinutes = 50,
                            ImageUrl = "https://img.freepik.com/free-photo/egyptian-food-traditional-dishes-served-table_2829-15184.jpg?w=740&t=st=1715627369~exp=1715630969~hmac=0c8b6e217b22077d0d2c3f6e5cf2b98d16a208f4849c20330a5f8f8c7e2820f1",
                            IsPromoted = false,
                            Name = "Egyptian Cuisine",
                            Rating = 4.5
                        });
                });

            modelBuilder.Entity("FoodDelivery.API.Models.RestaurantMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId")
                        .IsUnique();

                    b.ToTable("RestaurantMenus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 3,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 4,
                            RestaurantId = 4
                        },
                        new
                        {
                            Id = 5,
                            RestaurantId = 5
                        },
                        new
                        {
                            Id = 6,
                            RestaurantId = 6
                        },
                        new
                        {
                            Id = 7,
                            RestaurantId = 7
                        },
                        new
                        {
                            Id = 8,
                            RestaurantId = 8
                        },
                        new
                        {
                            Id = 9,
                            RestaurantId = 9
                        },
                        new
                        {
                            Id = 10,
                            RestaurantId = 10
                        });
                });

            modelBuilder.Entity("FoodDelivery.API.Models.FoodCategory", b =>
                {
                    b.HasOne("FoodDelivery.API.Models.RestaurantMenu", "RestaurantMenu")
                        .WithMany("Categories")
                        .HasForeignKey("RestaurantMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RestaurantMenu");
                });

            modelBuilder.Entity("FoodDelivery.API.Models.FoodItem", b =>
                {
                    b.HasOne("FoodDelivery.API.Models.FoodCategory", "FoodCategory")
                        .WithMany("Items")
                        .HasForeignKey("FoodCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodCategory");
                });

            modelBuilder.Entity("FoodDelivery.API.Models.Restaurant", b =>
                {
                    b.HasOne("FoodDelivery.API.Models.Address", "Address")
                        .WithMany("Restaurants")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("FoodDelivery.API.Models.RestaurantMenu", b =>
                {
                    b.HasOne("FoodDelivery.API.Models.Restaurant", "Restaurant")
                        .WithOne("Menu")
                        .HasForeignKey("FoodDelivery.API.Models.RestaurantMenu", "RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("FoodDelivery.API.Models.Address", b =>
                {
                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("FoodDelivery.API.Models.FoodCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FoodDelivery.API.Models.Restaurant", b =>
                {
                    b.Navigation("Menu")
                        .IsRequired();
                });

            modelBuilder.Entity("FoodDelivery.API.Models.RestaurantMenu", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
